In [1]:
from keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.


In [3]:
train_images.shape

(60000, 28, 28)

In [4]:
len(train_labels)

60000

In [26]:
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [6]:
test_images.shape

(10000, 28, 28)

In [7]:
len(test_labels)

10000

In [8]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [9]:
from keras import models
from keras import layers

In [11]:
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(10, activation='softmax'))
# Dense = Module ke koi b ejj khali nai ha, sub ek dosra sa connected ha
# Actvation Sirhi jasi graph ko slop ma convert kar data ha

In [12]:
network.compile(optimizer='rmsprop',
loss='categorical_crossentropy',
metrics=['accuracy'])
#optimizer ajust the wight

In [13]:
train_images = train_images.reshape((60000, 28 * 28))
train_images = train_images.astype('float32') / 255
test_images = test_images.reshape((10000, 28 * 28))
test_images = test_images.astype('float32') / 255

In [14]:
train_images

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [15]:
from keras.utils import to_categorical
train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)
# one node hincode
# label conver to 0 and 1 form

In [16]:
train_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [23]:
network.fit(train_images, train_labels, epochs=5, batch_size=128)
# Fit use for train network

Epoch 1/5
60000/60000 [==============================] - 5s 79us/step - loss: 0.0287 - acc: 0.9915
Epoch 2/5
60000/60000 [==============================] - 5s 76us/step - loss: 0.0218 - acc: 0.9935: 1
Epoch 3/5
60000/60000 [==============================] - 5s 77us/step - loss: 0.0167 - acc: 0.9951
Epoch 4/5
60000/60000 [==============================] - 5s 76us/step - loss: 0.0134 - acc: 0.9963
Epoch 5/5
60000/60000 [==============================] - 5s 76us/step - loss: 0.0095 - acc: 0.9974


In [21]:
test_acc = network.evaluate(test_images, test_labels)

10000/10000 [==============================] - 1s 56us/step


In [22]:
print('test_acc:', test_acc)

test_acc: [0.07327275509440806, 0.9779]
